### PR TITLE
Proposal for new cookbook version

### PR DESCRIPTION
**Pull request by rveznaver**
Hi,
This is a proposal for a new cookbook version which would utilise the Atlassian JIRA installer and enable a standalone JIRA installation without depending on any external cookbooks.
Please take a look, thanks!

### CODE REVIEW

**Comment by gsreynolds** [comment]
Hi @rveznaver, 

There is another JIRA cookbook which already has support for the JIRA installer: https://github.com/bflad/chef-jira

You may wish to integrate your work with the work already completed there? There has been recent activity on https://github.com/bflad/chef-confluence, but chef-jira could do with some love in addition to the couple of PRs I've submitted to it.

**Comment by rveznaver** [comment]
Thanks @gsreynolds,
I thought that one was not maintained any more (I also haven't found it on supermarket).

**Comment by juliandunn** [comment]
Looks cool. I will review, thanks! I agree that the `bflad/chef-jira` cookbook seems to be abandoned.

**Comment by juliandunn** [comment]
I have ceased maintaining this cookbook and given over the `jira` namespace to these folks: https://github.com/afklm/jira

**Pull request closed without merging**
